{
 "title": "CEOS Anycast Lab",
 "description": "Dashboard for the CEOS Anycast lab",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Spines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "clab-lab-spine1 - Interface traffic stats (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_eos_interface_stats_in_octets{source=\"clab-lab-spine1\", interface_name!=\"Management0\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}} - IN"
    },
    {
     "expr": "rate(gnmic_eos_interface_stats_out_octets{source=\"clab-lab-spine1\", interface_name!=\"Management0\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}} - OUT"
    }
   ]
  },
  {
   "title": "clab-lab-spine2 - Interface traffic stats (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_eos_interface_stats_in_octets{source=\"clab-lab-spine2\", interface_name!=\"Management0\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}} - IN"
    },
    {
     "expr": "rate(gnmic_eos_interface_stats_out_octets{source=\"clab-lab-spine2\", interface_name!=\"Management0\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}} - OUT"
    }
   ]
  },
  { "title": "Leafs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "clab-lab-leaf1 - Interface traffic stats (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_eos_interface_stats_in_octets{source=\"clab-lab-leaf1\", interface_name!=\"Management0\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}} - IN"
    },
    {
     "expr": "rate(gnmic_eos_interface_stats_out_octets{source=\"clab-lab-leaf1\", interface_name!=\"Management0\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}} - OUT"
    }
   ]
  },
  {
   "title": "clab-lab-leaf2 - Interface traffic stats (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_eos_interface_stats_in_octets{source=\"clab-lab-leaf2\", interface_name!=\"Management0\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}} - IN"
    },
    {
     "expr": "rate(gnmic_eos_interface_stats_out_octets{source=\"clab-lab-leaf2\", interface_name!=\"Management0\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}} - OUT"
    }
   ]
  },
  {
   "title": "clab-lab-leaf3 - Interface traffic stats (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_eos_interface_stats_in_octets{source=\"clab-lab-leaf3\", interface_name!=\"Management0\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}} - IN"
    },
    {
     "expr": "rate(gnmic_eos_interface_stats_out_octets{source=\"clab-lab-leaf3\", interface_name!=\"Management0\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}} - OUT"
    }
   ]
  },
  {
   "title": "clab-lab-leaf4 - Interface traffic stats (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(gnmic_eos_interface_stats_in_octets{source=\"clab-lab-leaf4\", interface_name!=\"Management0\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}} - IN"
    },
    {
     "expr": "rate(gnmic_eos_interface_stats_out_octets{source=\"clab-lab-leaf4\", interface_name!=\"Management0\"}[$__rate_interval])",
     "legendFormat": "{{interface_name}} - OUT"
    }
   ]
  }
 ]
}