---
# Base configuration for Nornir
# Can also just do this programmatically in a Python script
inventory:
    plugin: SimpleInventory
    options:
        host_file: "/app/inventory/hosts.yml"
        group_file: "/app/inventory/groups.yml"
        defaults_file: "/app/inventory/defaults.yml"
runner:
    plugin: threaded
    options:
        num_workers: 10
logging:
    log_file: "/app/log/nornir.log"