all:
  vars:
    # The generated inventory is assumed to be used from the clab host.
    # Hence no http proxy should be used. Therefore we make sure the http
    # module does not attempt using any global http proxy.
    ansible_httpapi_use_proxy: false
  children:
    juniper_crpd:
      vars:
        ansible_connection: local
        ansible_user: root
        ansible_password: clab123
      hosts:
        clab-lab-crpd1:
          ansible_host: 172.20.0.11
        clab-lab-crpd2:
          ansible_host: 172.20.0.12
        clab-lab-crpd3:
          ansible_host: 172.20.0.13
        clab-lab-crpd4:
          ansible_host: 172.20.0.14
        clab-lab-crpd5:
          ansible_host: 172.20.0.15
        clab-lab-crpd6:
          ansible_host: 172.20.0.16
        clab-lab-crpd7:
          ansible_host: 172.20.0.17
        clab-lab-crpd8:
          ansible_host: 172.20.0.18
        clab-lab-crpd9:
          ansible_host: 172.20.0.19
    linux:
      hosts:
        clab-lab-ansible:
          ansible_host: 172.20.0.100