---
ceos1:
  username: admin
  password: admin
  platform: eos
  hostname: 172.20.0.12
  groups:
    - dev
  data:
    site: lab
    role: router
    nested_data:
      a_dict:
        a: 1
        b: 2
      a_list: [1, 2]
      a_string: "test"
  connection_options:
    scrapli:
      port: 22
      extras:
        ssh_config_file: True
        auth_strict_key: False
crpd1:
  username: root
  password: clab123
  platform: junos
  hostname: 172.20.0.11
  groups:
    - dev
  data:
    site: lab
    role: router
  connection_options:
    scrapli:
      port: 22
      extras:
        ssh_config_file: True
        auth_strict_key: False
srl1:
  username: admin
  password: NokiaSrl1!
  platform: nokia_srlinux
  hostname: 172.20.0.13
  groups:
    - dev
  data:
    site: lab
    role: router