---
ceos1:
  username: admin
  password: admin
  platform: eos
  hostname: 172.20.0.12
  groups:
    - cmh
  data:
    site: cmh
    role: host
    type: host
    nested_data:
      a_dict:
        a: 1
        b: 2
      a_list: [1, 2]
      a_string: "asdasd"
crpd1:
  username: root
  password: clab123
  platform: junos
  hostname: 172.20.0.11
srl1:
  username: admin
  password: NokiaSrl1!
  platform: nokia_srlinux
  hostname: 172.20.0.13