---
ceos1:
    username: admin
    password: admin
    platform: eos
    hostname: 172.20.0.12
crpd1:
    username: root
    password: clab123
    platform: junos
    hostname: 172.20.0.11
srl1:
    username: admin
    password: NokiaSrl1!
    platform: nokia_srlinux
    hostname: 172.20.0.13