---
# These should be in vault, but as this is a demo, we'll just put them here
netbox_url: "http://netbox:8080"
netbox_token: a4bd2e9bf74869feb061eba14b090b4811353d9f
validate_certs: false
state: present

manufacturers:
  - name: Cisco
    slug: cisco
    description: Cisco Systems, Inc.
  - name: Juniper
    slug: juniper
    description: Juniper Networks, Inc.
  - name: Arista
    slug: arista
    description: Arista Networks, Inc.
  - name: Opengear
    slug: opengear
    description: Opengear, Inc.

# Just grab whatever devices you need from the netbox community github
# https://github.com/netbox-community/devicetype-library
device_types:
  - manufacturer: Opengear
    model: OM2216
    slug: opengear-om2216
    part_number: OM2216
    u_height: 1
    is_full_depth: false
    weight: 3.5
    weight_unit: kg
    airflow: passive
    comments: '[Operations Manager OM2200 Data Sheet](https://resources.opengear.com/om/datasheets/om2200/)'
    console-ports:
      - name: Console
        type: rj-45
      - name: USB Console
        type: usb-micro-b
    console-server-ports:
      - name: Port 1
        type: rj-45
      - name: Port 2
        type: rj-45
      - name: Port 3
        type: rj-45
      - name: Port 4
        type: rj-45
      - name: Port 5
        type: rj-45
      - name: Port 6
        type: rj-45
      - name: Port 7
        type: rj-45
      - name: Port 8
        type: rj-45
      - name: Port 9
        type: rj-45
      - name: Port 10
        type: rj-45
      - name: Port 11
        type: rj-45
      - name: Port 12
        type: rj-45
      - name: Port 13
        type: rj-45
      - name: Port 14
        type: rj-45
      - name: Port 15
        type: rj-45
      - name: Port 16
        type: rj-45
      - name: USB A
        type: usb-a
      - name: USB B
        type: usb-a
      - name: USB C
        type: usb-a
      - name: USB D
        type: usb-a
      - name: USB E
        type: usb-a
      - name: USB F
        type: usb-a
      - name: USB G
        type: usb-a
      - name: USB H
        type: usb-a
      - name: Front Upper USB
        type: usb-a
      - name: Front Lower USB
        type: usb-a
    power-ports:
      - name: PS1
        type: iec-60320-c14
        allocated_draw: 30
      - name: PS2
        type: iec-60320-c14
        allocated_draw: 30
    interfaces:
      - name: eth0
        type: 1000base-t
        mgmt_only: true
      - name: eth1
        type: 1000base-t
        mgmt_only: true
  - manufacturer: Juniper
    model: EX4400-48T
    part_number: EX4400-48T
    slug: juniper-ex4400-48t
    u_height: 1
    airflow: front-to-rear
    weight: 13.01
    weight_unit: lb
    comments: '[Juniper EX4400 Hardware Guide](https://www.juniper.net/documentation/us/en/hardware/ex4400/topics/topic-map/ex4400-system-overview.html)'
    interfaces:
      - name: me0
        type: 1000base-t
        mgmt_only: true
      - name: ge-0/0/0
        type: 1000base-t
      - name: ge-0/0/1
        type: 1000base-t
      - name: ge-0/0/2
        type: 1000base-t
      - name: ge-0/0/3
        type: 1000base-t
      - name: ge-0/0/4
        type: 1000base-t
      - name: ge-0/0/5
        type: 1000base-t
      - name: ge-0/0/6
        type: 1000base-t
      - name: ge-0/0/7
        type: 1000base-t
      - name: ge-0/0/8
        type: 1000base-t
      - name: ge-0/0/9
        type: 1000base-t
      - name: ge-0/0/10
        type: 1000base-t
      - name: ge-0/0/11
        type: 1000base-t
      - name: ge-0/0/12
        type: 1000base-t
      - name: ge-0/0/13
        type: 1000base-t
      - name: ge-0/0/14
        type: 1000base-t
      - name: ge-0/0/15
        type: 1000base-t
      - name: ge-0/0/16
        type: 1000base-t
      - name: ge-0/0/17
        type: 1000base-t
      - name: ge-0/0/18
        type: 1000base-t
      - name: ge-0/0/19
        type: 1000base-t
      - name: ge-0/0/20
        type: 1000base-t
      - name: ge-0/0/21
        type: 1000base-t
      - name: ge-0/0/22
        type: 1000base-t
      - name: ge-0/0/23
        type: 1000base-t
      - name: ge-0/0/24
        type: 1000base-t
      - name: ge-0/0/25
        type: 1000base-t
      - name: ge-0/0/26
        type: 1000base-t
      - name: ge-0/0/27
        type: 1000base-t
      - name: ge-0/0/28
        type: 1000base-t
      - name: ge-0/0/29
        type: 1000base-t
      - name: ge-0/0/30
        type: 1000base-t
      - name: ge-0/0/31
        type: 1000base-t
      - name: ge-0/0/32
        type: 1000base-t
      - name: ge-0/0/33
        type: 1000base-t
      - name: ge-0/0/34
        type: 1000base-t
      - name: ge-0/0/35
        type: 1000base-t
      - name: ge-0/0/36
        type: 1000base-t
      - name: ge-0/0/37
        type: 1000base-t
      - name: ge-0/0/38
        type: 1000base-t
      - name: ge-0/0/39
        type: 1000base-t
      - name: ge-0/0/40
        type: 1000base-t
      - name: ge-0/0/41
        type: 1000base-t
      - name: ge-0/0/42
        type: 1000base-t
      - name: ge-0/0/43
        type: 1000base-t
      - name: ge-0/0/44
        type: 1000base-t
      - name: ge-0/0/45
        type: 1000base-t
      - name: ge-0/0/46
        type: 1000base-t
      - name: ge-0/0/47
        type: 1000base-t
      - name: et-0/1/0
        type: 100gbase-x-qsfp28
      - name: et-0/1/1
        type: 100gbase-x-qsfp28
    console-ports:
      - name: Console
        type: rj-45
      - name: Front Console
        type: usb-c
    module-bays:
      - name: Fan Module 0
        weight: 0.26
        weight_unit: lb
      - name: Fan Module 1
        weight: 0.26
        weight_unit: lb
      - name: Extension module
        position: '2'
      - name: PSU0
        position: '0'
      - name: PSU1
        position: '1'

device_roles:
  - name: Access Switch
    slug: access-switch
    color: ff0000
    vm_role: false
  - name: Console Server
    slug: console-server
    color: 00ff00
    vm_role: false

devices:
  - name: amer0001-oob-01
    device_type: opengear-om2216
    device_role: console-server
    site: amer0001
    rack: amer0001-l1-comms-r1
    position: 42
    face: front
    tenant: infrastructure-team
  - name: amer0001-acc-swi-01
    device_type: juniper-ex4400-48t
    device_role: access-switch
    site: amer0001
    rack: amer0001-l1-comms-r1
    position: 39
    face: front
    tenant: infrastructure-team
  - name: amer0001-ex4400-2
    device_type: juniper-ex4400-48t
    device_role: access-switch
    site: amer0001
    rack: amer0001-l1-comms-r1
    position: 38
    face: front
    tenant: infrastructure-team
