---
- name: Device configuration to be applied
  ansible.builtin.debug:
    msg: "{{ lookup('template', '../templates/conf_junos_device.j2') }}"

- name: Apply device configuration
  arista.eos.eos_config:
    src: "../templates/conf_junos_device.j2"
  vars:
    ansible_command_timeout: 60