---
# Specific Device configuration
#
# Interfaces, IPs, Routing, etc.
system:
  type: "router"

# Interfaces (Management already done by Containerlab)
interfaces:
  - if: "Loopback0"
    desc: "Underlay Loopback"
    ipv4: "10.0.0.22/32"
    ipv6: "2001:db8:c2::1/128"
  - if: "Loopback1"
    desc: "VTEP Loopback"
    ipv4: "10.0.1.22/32"
  - if: "Ethernet1"
    desc: "clab-lab-leaf1:Ethernet1 --> clab-lab-spine1:Ethernet2"
    ipv6: "LLA"
  - if: "Ethernet2"
    desc: "clab-lab-leaf1:Ethernet2 --> clab-lab-spine2:Ethernet2"
    ipv6: "LLA"

# Routing
bgp:
  router_id: 10.0.0.22
  type: "leaf"
  local_as: 65102
  underlay_name: "PG_UNDERLAY"
  underlay_as: 65000
  overlay_name: "PG_OVERLAY"
  overlay_as: 65000
  underlay_interfaces:
    - if: "Ethernet1"
    - if: "Ethernet2"
  overlay_interfaces:
    - ip: "10.0.0.11"
    - ip: "10.0.0.12"
        
# VXLAN
vxlan:
  mac_address: "001c.7301.1eaf"
  vr: True
  range_start: 129
  range_end: 256
  common:
    lacp_id: 5
    host_if: "Ethernet5"
    desc: "clab-lab-leaf2:eth5 --> clab-lab-host1:eth2"
    evpn_id: "0050:0900:1eaf:1200:0000"
    evpn_rt: "50:09:00:1e:af:12"
  tenants:
    - id: "TENANT-A"
      host_if: "Ethernet5"
      l2_vlans: [101, 102]
      l3_vlan:
        id: 100
        loop_ip: "172.16.100.12"
        gw_ip: "192.168.100.1/24"
        vni: 1000
    - id: "TENANT-B"
      host_if: "Ethernet5"
      l2_vlans: [201, 202]
      l3_vlan:
        id: 200
        loop_ip: "172.16.200.12"
        gw_ip: "192.168.200.1/24"
        vni: 2000
